language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
  
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"

install: true
script: 
#!/usr/bin/env sh
- set -e
 
# Define some variables 
- export IJ_PATH="$HOME/Fiji.app"
- export URL="http://sites.imagej.net/$UPDATE_SITE/"
- export IJ_LAUNCHER="$IJ_PATH/ImageJ-linux64"
- export PATH="$IJ_PATH:$PATH"
 
# Install ImageJ
- mkdir -p $IJ_PATH/
- cd $HOME/
- wget --no-check-certificate https://downloads.imagej.net/fiji/latest/fiji-linux64.zip
- unzip fiji-linux64.zip
- cd $TRAVIS_BUILD_DIR/
- realpath /ExampleImage
- ls -l
- cd ..
- ls -l
- cd ..
- ls -l
- cd ..
- ls -l
 
# Install the package
#- unzip $TRAVIS_BUILD_DIR/Cluster_Analysis.zip -d $HOME/Fiji.app/plugins
#- cd $HOME/Fiji.app/plugins/
#- ls -l
- mv $TRAVIS_BUILD_DIR/Cluster_Analysis.py $HOME/Fiji.app/plugins/
- mv $TRAVIS_BUILD_DIR/sqlite-jdbc-3.21.0.jar $HOME/Fiji.app/plugins/
#- xvfb-run -a $HOME/Fiji.app/ImageJ-linux64 $HOME/Fiji.app/plugins/Cluster_Analysis.py h $TRAVIS_BUILD_DIR/ExampleImage
- $HOME/Fiji.app/ImageJ-linux64 --ij2 --headless --run $HOME/Fiji.app/plugins/Cluster_Analysis.py 'file="TRAVIS_BUILD_DIR/Cluster-Analysis-Plugin"'



