language: python
python:
  - "2.7"
sudo: required
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
services:
 - xvfb

env:
 - TEST_FOLDER=/home/travis/build/dcolam/Cluster-Analysis-Plugin/ExampleImage FIJI_FOLDER=/home/travis/Fiji.app JAVA_OPTS=-Xmx2g

before_install:
 - export JYTHON_URL='http://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.7.0/jython-installer-2.7.0.jar'
 - wget $JYTHON_URL -O jython_installer-2.7.0.jar; java -jar jython_installer-2.7.0.jar -s -d $HOME/jython; export PATH=$HOME/jython/bin/jython:$PATH;
install: true

script:
#!/usr/bin/env sh
- set -e
# Define some variables
- export IJ_PATH="$HOME/Fiji.app"
- export URL="http://sites.imagej.net/$UPDATE_SITE/"
- export IJ_LAUNCHER="$IJ_PATH/ImageJ-linux64"
- export PATH="$IJ_PATH:$PATH"

# Install ImageJ
- mkdir -p $IJ_PATH/
- cd $HOME/
- wget --no-check-certificate https://downloads.imagej.net/fiji/latest/fiji-linux64.zip
- unzip fiji-linux64.zip
- cd $TRAVIS_BUILD_DIR/
- sudo apt-get install realpath
- realpath $TRAVIS_BUILD_DIR/ExampleImage
- realpath $HOME/Fiji.app
- mv $TRAVIS_BUILD_DIR/Cluster_Analysis/ $HOME/Fiji.app/plugins/
- cd $HOME/Fiji.app/plugins/Cluster_Analysis/
- export CLASSPATH=$HOME/Fiji.app/jars/sqlite-jdbc-3.21.0.jar
#- mv $TRAVIS_BUILD_DIR/ExampleImage/ini.cfg $HOME/Fiji.app/plugins/Cluster_Analysis
- mv $TRAVIS_BUILD_DIR/sqlite-jdbc-3.21.0.jar $HOME/Fiji.app/jars/
- xvfb-run -a $HOME/Fiji.app/ImageJ-linux64 --ij2 --headless --run $HOME/Fiji.app/plugins/Cluster_Analysis/Cluster_Analysis_BETA_v3.py 'expath="/home/travis/build/dcolam/Cluster-Analysis-Plugin/ExampleImage",expName="ini",headless="True",measure="False",c="Red",colSel="WHITE", colParticles="WHITE", colColoc="WHITE"'
- xvfb-run -a $HOME/Fiji.app/ImageJ-linux64 --ij2 --headless --run $HOME/Fiji.app/plugins/Cluster_Analysis/Load_Custom_ini_File.py 'inifile="/home/travis/build/dcolam/Cluster-Analysis-Plugin/ExampleImage/ini.cfg"'
- xvfb-run -a $HOME/jython/bin/jython $TRAVIS_BUILD_DIR/Testsuits/tests.py -J-Xmx2g

#- xvfb-run -a $HOME/Fiji.app/ImageJ-linux64 --ij2 --run $HOME/Fiji.app/plugins/Cluster_Analysis_travis_Tester.py 'filepath="/home/travis/build/dcolam/Cluster-Analysis-Plugin/ExampleImage"'



